### ISSUE TITLE
Highscore Screen

### ISSUE THREAD

**Issue by adri** [liip/guess-the-liiper-ios#15]
- extend GuessAPI by highscore 
- Highscore Screen

![screen shot 2015-06-11 at 11 05 59](https://cloud.githubusercontent.com/assets/133832/8103589/e4302cd0-1029-11e5-906c-c4e87c734bdd.png)

**Comment by syzer** [comment]
+1 :)

**Comment by adri** [comment]
Progress so far.
![screen shot 2015-06-18 at 16 39 09](https://cloud.githubusercontent.com/assets/133832/8233825/9a81c080-15d8-11e5-9e66-a88e977fcef6.png)

**Comment by adri** [comment]
![ios simulator screen shot 25 jun 2015 19 39 24](https://cloud.githubusercontent.com/assets/133832/8361226/1abb2630-1b72-11e5-8b36-aa8172362091.png)

**Comment by adri** [comment]
Maybe use https://github.com/brentvatne/react-native-scrollable-tab-view
